<h1>Настройка таблицы <code><?php echo $table->__get('name');?></code></h1>

<div class="panel panel-default">
  <div class="panel-heading">Основные параметры</div>
  <div class="panel-body">
	<div class="form-group">
		<label for="name">Название таблицы</label>
	      <input type="text" id="name" value="<?php echo $table->__get('name')?>" class="form-control" placeholder="Название таблицы">
	</div>
	<div class="form-group">
		<label for="description">Описание таблицы</label>
	      <textarea id="description" placeholder="Описание таблицы" class="form-control"><?php echo $table->__get('description')?></textarea>
	</div>
	<div class="form-group">
		<label for="entity">Класс таблицы</label>
		<select name="entity" id="entity" class="form-control">
			<?php foreach ($entities as $k=>$v){?>
			<option value="<?php echo $v;?>"<?php if($table->__get('entity')==$v) echo " selected";?>><?php echo $v;?></option>
			<?php }?>
		</select>
	</div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Место отображения</div>
  <div class="panel-body">
  
	 <div class="checkbox">
	    <label>
	      <input type="checkbox" id="iMonitor" value="iMonitor" class="adminPlace"<?php if($table->__get('iMonitor')) echo " checked"?>> Я-Монитор (сводка)
	    </label>
	    <label>
	      <input type="checkbox" id="dataManagement" value="dataManagement" class="adminPlace"<?php if($table->__get('dataManagement')) echo " checked"?>> Управление данными
	    </label>
	  </div>
	  
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Связи</div>
  <div class="panel-body">
	 <?php foreach ($entity_params as $k=>$ent) {?>
  	 <div class="row">
		<div class="col-md-3"><strong><?php echo $ent['targetEntityParams']->table['options']['comment'];?></strong></div>
		<div class="col-md-3">отображать поля при поиске:</div>
		<div class="col-md-6">
			<?php foreach ($ent['targetEntityParams']->fieldMappings as $field_name=>$f_param) {?>
				
			<?php }?>
		</div>
	 </div>
	 <?php }?>
	  
  </div>
</div>

<div class="row">
	<div class="col-md-6">
		<a href="#" class="saver btn btn-success">Сохранить</a>
	</div>
	<div class="col-md-6 text-right">
		<a href="#" class="canceler btn btn-info">Отмена</a>
	</div>
</div>

<script type="text/javascript">
<!--

$(document).ready(function(){

	$('.saver').click(function(){

		var request = {};
		
		id = <?php echo $table->__get('id');?>;
		request.table_id = id;
		request.iMonitor = $('#iMonitor').prop('checked');
		request.dataManagement = $('#dataManagement').prop('checked');
		request.name = $('#name').val();
		request.description = $('#description').val();
		request.entity = $('#entity').val();
			
		$.ajax({
			  url: "<?php echo $this->url('zfcadmin/tsv-directory/table',array("action"=>"saveConfigure"))?>",
			  type: "POST",
			  data: JSON.stringify(request),
			  processData: false,
			  dataType: "json",
			  success:function(a) { 

				  if(a.error)
					  alert(a.error);
				  else
					  window.location.href='<?php echo $this->url('zfcadmin/tsv-directory/table')?>'
				  
			  },
			  error:function() {
				  alert('Ошибка отправки сообщения на сервер');
			  }
		});

		
	});
		
	$('.canceler').click(function(){
		window.location.href = '<?php echo $this->url('zfcadmin/tsv-directory/table');?>';
	});
		
});

//-->
</script>