	<table class="table table-bordered">
      <thead>
        <tr>
          <th>Выберете</th>
        <?php foreach ($fields as $k=>$v) {?>
          <th><?php echo $v;?></th>
        <?php }?>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($data as $d) {?>
        <tr>
          <td width="100" rowId="<?php echo $d['id']?>"><input onchange="add_data(this);" class="add_data" field="<?php echo $field;?>" type="checkbox" value='<?php echo $d['id']?>'></td>
        <?php foreach ($fields as $k=>$v) {?>
          <td><?php 
          echo $d[$k];?></td>
        <?php }?>
        </tr>
      <?php }?>
      </tbody>
    </table>