<?php echo $this->partial('partials/section-list', array('sections' => $sections,'selectedSection'=>$this->selectedSection,'dataManagement'=>$dataManagement,"dataManagement_id"=>$dataManagement_id));?>

<h1><code><?php echo $table_config->__get('name')?></code></h1>
<div>
	<i>
		<?php echo $table_config->__get('description');?>
	</i>
</div>
<div>
	<a class="btn btn-link" href="<?php echo $this->url("zfcadmin/tsv-directory/table",array('action'=>"changeViewType","id"=>$table_config->__get('id')));?>">Изменить вид</a>
</div>
<br>
<div class="row">
	<div class="col-md-12">
		<a class="btn btn-success" href="<?php echo $this->url("zfcadmin/tsv-directory/table",array('action'=>"addData","id"=>$table_config->__get('id')));?>">Добавить</a>
	</div>
</div>
<br>
<?php if($table->getItemCountPerPage()==1){?>
<table class="table table-bordered">
    <?php foreach($table as $row){ ?>
    <tr>
    	<td colspan='2'>
	    	<a class="btn btn-info" href="<?php echo $this->url("zfcadmin/tsv-directory/table",array('action'=>"editData","id"=>$table_config->__get('id'),"idr"=>$this->TgetValue($row,'id')));?>"/>Редактировать</a>
	    	<a class="btn btn-danger" onClick="if(confirm('Вы уверены?')){document.location=this.href} return false;" href="<?php echo $this->url("zfcadmin/tsv-directory/table",array('action'=>"deleteData","id"=>$table_config->__get('id'),"idr"=>$this->TgetValue($row,'id')));?>"/>Удалить</a>
		</td>
	</tr>
	<?php foreach($table_params->reflFields as $k=>$param){ ?>
		<tr>
		    <td><?php echo $this->TgetFTitle($table_params,$param->name)?></td><td><?php echo $this->TgetValue($row,$param->name)?></td>
		</tr>
    <?php }}?>
</table>
<?php } else{ 

//     var_dump($table_params);
    
    ?>
<table class="table table-bordered">
      <thead>
        <tr>
          <th rowspan=2><input type="checkbox" id="selectAll"></th>
        <?php foreach ($table_params->reflFields as $k=>$param) {?>
          <th rowspan=<?php if(
              isset($table_params->associationMappings[$k]) && 
              $table_config->is_subtable($table_params->associationMappings[$k]['targetEntity'])) 
          { echo 1; echo " colspan=".$this->TgetSubtitlesCount($table_config->getTitleSubtableByData($table_params->associationMappings[$k]['targetEntity']));} else echo 2;?>><?php echo $this->TgetFTitle($table_params,$param->name);?></th>
        <?php }?>
          <th rowspan=2>&nbsp;</th>
          <th rowspan=2>&nbsp;</th>
        </tr>
        <?php if(count($table_config->__get('subtables'))){?>
        <tr>
          <?php foreach ($table_config->__get('subtables') as $sub)
                    foreach ($this->TgetSubtitles($sub->__get('title_class')) as $title){?>
              <th><?php echo $title->__get('name');?></th>
          <?php }?>
          </tr>
        <?php }?>
      </thead>
      <tbody>
<?php foreach ($table as $row){
	?>
        <tr>
          <td width="30"><input type="checkbox" class="selectAll"></td>
        <?php foreach ($table_params->reflFields as $k=>$param) {?>
          <td<?php if(
              isset($table_params->associationMappings[$k]) && 
              $table_config->is_subtable($table_params->associationMappings[$k]['targetEntity'])) 
          { echo " colspan=".$this->TgetSubtitlesCount($table_config->getTitleSubtableByData($table_params->associationMappings[$k]['targetEntity']));} ?>><?php echo $this->TgetValue($row,$param->name);?></td>
        <?php }?>
    	  <td><a href="<?php echo $this->url("zfcadmin/tsv-directory/table",array('action'=>"editData","id"=>$table_config->__get('id'),"idr"=>$this->TgetValue($row,'id')));?>" class="glyphicon glyphicon-edit"></td>
    	  <td><a onClick="if(confirm('Are you sure?')){document.location=this.href} return false;" href="<?php echo $this->url("zfcadmin/tsv-directory/table",array('action'=>"deleteData","id"=>$table_config->__get('id'),"idr"=>$this->TgetValue($row,'id')));?>" class="glyphicon glyphicon-trash"></td>
        </tr>
<?php }?>
      </tbody>
    </table>
<?php } ?>
<?php
 
echo $this->paginationcontrol(
			$table,
			'Sliding',
			'partials/helper/paginator',
			array(
				'route_params' => array(
					'action'=>'dataManagement',
					'id'=>$table_config->__get('id'),
					'idr'=>0,
				)
			)
);
?>
    
<script type="text/javascript">
<!--

$('#selectAll').click(function(){
	$('.selectAll').prop('checked',$(this).prop('checked'));
}); 

//-->
</script>
    
