<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Создать новый справочник
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
          <h3 style="margin: 0px 0px 10px 0px;">Создать новый справочник</h3>
          <form method="post">
		      <div class="form-group">
			    <label for="name">Название</label>
			    <input type="text" class="form-control" id="name" name="name" placeholder="Укажите название справочника" required>
			  </div>
		      <div class="form-group">
			    <label for="description">Описание</label>
			    <textarea class="form-control" id="description" name="description" placeholder="Укажите описание к справочнику (не обязательно)"></textarea>
			  </div>
			  <button type="submit" class="btn btn-default">Создать</button>
		  </form>
      </div>
    </div>
  </div>
</div>

<div class="row">
<?php foreach ($tables as $table){?>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3 style="margin-top: 0px;"><?php echo $table->__get('name');?></h3>
        <p><?php echo $table->__get('description');?></p>
        <?php if(!count($table->__get('TableFields'))){?>
        <p><a href="<?php echo $this->url('zfcadmin/tsv-directory/table',array("action"=>"configure","id"=>$table->__get('id')));?>" class="btn btn-warning" role="button">Настроить таблицу</a></p>
        <?php }else{?>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
        <?php }?>
      </div>
    </div>
  </div>
<?php }?>
</div>
<?php 
if(!count($tables)) {
?>
<h3>Справочники отсутствуют, воспользуйтесь формой создания</h3>
<?php 
}
?>