

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Создать новый справочник
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
          <h3 style="margin: 0px 0px 10px 0px;">Создать новый справочник</h3>
          <form method="post">
		      <div class="form-group">
			    <label for="name">Название</label>
			    <input type="text" class="form-control" id="name" name="name" placeholder="Укажите название справочника" required>
			  </div>
			  <button type="submit" class="btn btn-default">Создать</button>
		  </form>
      </div>
    </div>
  </div>


</div>