<?php 

@preg_match_all("/['\"]([a-zA-Z0-9\+\.\,\s]+)['\"]/", $field_params['columnDefinition'],$match);

if(isset($match[1]))
{
	$var_values = $match[1];
	$var_names	= explode(":",$field_params['options']['enumNames']);
	
	if(count($var_names) != count($var_values))
	{
		echo "Ошибка Enum параметров. Перечень возможных значений не соответсвует перечню имен. Проверьте класс";
	}
	else
	{
		foreach ($var_values as $k=>$v)
			$var[$v] = $var_names[$k];
	
		if(isset($var) && isset($var[$data->__get($field)]))
			echo $var[$data->__get($field)];

		
	}
}
else 
	echo "Ошибка Enum параметров. Перечень значений для enum не задан";


?>