<?php if(!isset($this->TsvKey)) $this->TsvKey=' '?>
<div class="btn-group pull-right">
	<button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">Добавить контент <span class="caret"></span></button>
	<ul class="dropdown-menu add-content-btns" role="menu">
		<li><a title="Простой текст или число" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$section_id,"content_type"=>"TsvStext","b64TsvKey"=>urlencode(base64_encode($this->TsvKey))));?>"><img src="http://serveon.ru/img/SimpleText.png" alt="Простой текст или число">Простой текст или число</a></li>
		<li><a title="HTML текст" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$section_id,"content_type"=>"TsvText","b64TsvKey"=>urlencode(base64_encode($this->TsvKey))));?>"><img src="http://serveon.ru/img/HtmlText.png" alt="HTML-Текст">HTML-Текст</a></li>
		<li><a title="Галерея файлов и изображений" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$section_id,"content_type"=>"TsvFile","b64TsvKey"=>urlencode(base64_encode($this->TsvKey))));?>"><img src="http://serveon.ru/img/ImageGalary.png" alt="Галерея файлов">Галерея файлов (изображений)</a></li>
		<li><a title="Карусель" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$section_id,"content_type"=>"TsvCarousel","b64TsvKey"=>urlencode(base64_encode($this->TsvKey))));?>"><img src="http://serveon.ru/img/Carousel.png" alt="Карусель">Карусель</a></li>
	</ul>
</div>