<ul class="nav nav-pills">
  <li>
    <a href="<?php echo $this->url("zfcadmin/tsv-directory/default", array("action"=>"addSection","controller"=>"tsvDirectory"));?>"><span class="glyphicon glyphicon-plus" title="Добавить новый раздел"></span></a>
  </li>
<?php foreach ($this->sections as $row){?>
  <li <?php if($this->selectedSection==$row->__get('id')){?> class="active"<?php }?>><a href="<?php echo $this->url('zfcadmin/tsv-directory/section-view', array('action'=>'viewSection','id'=>$row->__get('id'))) ?>"><?php echo $row->__get('secName');?></a></li>
<?php }?>
<?php foreach ($this->dataManagement as $row){?>
  <li <?php if($this->dataManagement_id==$row->__get('id')){?> class="active"<?php }?>><a title="Справочник" href="<?php echo $this->url('zfcadmin/tsv-directory/table', array('action'=>'dataManagement','id'=>$row->__get('id'))) ?>"><?php echo $row->__get('name');?> <span class="glyphicon glyphicon glyphicon-th-large" aria-hidden="true"></span></a></li>
<?php }?>
<li class="disabled"><a href="<?php echo $this->url('zfcadmin/tsv-directory/paginator', array('action'=>'sections'))?>" style="cursor:pointer;font-size:10px;margin-top:4px;">Править/Удалить</a></li>
</ul>

<div class="pull-right">
	<ul class="nav nav-pills">
	</ul>
</div>