<br>
<div class="row">
	<div class="col-md-1" style="font-size:18px;margin-top:5px;">
    	Название
	</div>
	<div class="col-md-11">
	   	<input class="form-control" type="text" id="TsvCarousel" name="TsvCarousel" placeholder="Отображаемое имя карусели" value="<?php if(isset($content_arr['TsvCarousel'])) echo $content_arr['TsvCarousel'];?>" required>
	</div>
</div>

<h1>Загрузите изображения для последующего использования</h1>
(вы также можете сделать это позже или не выполнять загрузку файлов вообще)
<?php 

if(isset($content_arr) && isset($content_arr['id']) && $content_arr['id'])
	$id = $content_arr['id'];
else 
	$id = 0;
?>
 <iframe src="<?php echo $this->url("zfcadmin/tsv-directory/uploader-form",array("id"=>$id,"entity_parent"=>"TsvCarousel","entity_store"=>"TsvCarouselImages")) ?>?rand=<?php echo rand(-65534, 65534)?>" width="100%" height="460">
    Ваш браузер не поддерживает плавающие фреймы!
 </iframe>