<br>
<div class="row">
	<div class="col-md-1" style="font-size:18px;margin-top:5px;">
    	Название
	</div>
	<div class="col-md-11">
	   	<input class="form-control" type="text" id="TsvCarousel" name="TsvCarousel" placeholder="Отображаемое имя карусели" value="<?php if(isset($content_arr['TsvCarousel'])) echo $content_arr['TsvCarousel'];?>" required>
	</div>
</div>

<h2>Укажите стратегию использования</h2>
<div class="panel panel-default">
  <div class="panel-body">
	    <label class="radio-inline">
		  <input type="radio" name="strategy" id="s1" value="1"<?php if(!isset($content_arr['strategy']) || $content_arr['strategy']!=2) echo " checked";?> required> Использовать изображения как фон + HTML текст
		</label>
		<label class="radio-inline">
		  <input type="radio" name="strategy" id="s2" value="2"<?php if(isset($content_arr['strategy']) && $content_arr['strategy']==2) echo " checked";?> required> Использовать изображения как элементы карусели
		</label>

  </div>
</div>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>Параметр настройки</th>
			<th>Значение параметра</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				Высота карусели (px)
			</td>
			<td>
				<input type="text" name="height" value="<?php if(isset($content_arr['height'])) echo $content_arr['height'];?>">
			</td>
		</tr>
		<tr class="hidden" id='strategys2'>
			<td>
				Количество картинок на одной странице (1-12)
			</td>
			<td>
				<input type="text" name="count_on_page" id="count_on_page" value="<?php if(isset($content_arr['count_on_page'])) echo $content_arr['count_on_page'];?>">
			</td>
		</tr>
	</tbody>
</table>

<script>
function set_fields_s2()
{
	if($('#s2').prop('checked')==true)
	{
		$('#strategys2').removeClass('hidden');
		$('#count_on_page').prop('disabled',false);
	}
	else
	{
		$('#strategys2').addClass('hidden');
		$('#count_on_page').prop('disabled',true);
	}
	
}

$("input[name='strategy']").change(function(){set_fields_s2();});
set_fields_s2();
</script>

<h2>Загрузите изображения для последующего использования</h2>
(вы также можете сделать это позже или не выполнять загрузку файлов вообще)
<?php 

if(isset($content_arr) && isset($content_arr['id']) && $content_arr['id'])
	$id = $content_arr['id'];
else 
	$id = 0;
?>
 <iframe src="<?php echo $this->url("zfcadmin/tsv-directory/uploader-form",array("id"=>$id,"entity_parent"=>"TsvCarousel","entity_store"=>"TsvCarouselImage")) ?>?rand=<?php echo rand(-65534, 65534)?>" width="100%" height="460">
    Ваш браузер не поддерживает плавающие фреймы!
 </iframe>