<!--
See http{//developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php 



if ($this->pageCount)	{ ?>

<div align="center">
  <ul class="pagination pagination-sm">
    <li <?php if (!isset($this->previous)){ ?>class="disabled"<?php }?>><a href="<?php echo $this->url($this->route, array_merge(array('page' => $this->previous),$route_params)); ?>">«</a></li>
	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page){ ?>
	    <li  <?php if ($page == $this->current){ ?>class="active"<?php }?>><a href="<?php echo $this->url($this->route, array_merge(array('page' => $page),$route_params)); ?>"><?php echo $page; ?></a></li>
	<?php } ?>
    <li <?php if (!isset($this->next)){ ?>class="disabled"<?php }?>><a href="<?php echo $this->url($this->route, array_merge(array('page' => $this->next),$route_params)); ?>">»</a></li>
	</ul>
</div>

<?php }?>
