<script src="//cdn.ckeditor.com/4.4.2/full/ckeditor.js"></script>
<p><?php echo $content->__get('TsvCarousel');?></p>




<?php if($content->__get('strategy') == 2) {

	if($content->__get('count_on_page'))
		$count_per_page = $content->__get('count_on_page');	
	else 
		$count_per_page = 4;
	
$elements = array();
$i = 0;

foreach ($content->__get('TsvCarouselImages') as $page){
	if(count($elements[$i])>=$count_per_page)
		$i++;
	
	$elements[$i][] = $page;
}
?>


<style>
.carousel-control {
	width: 50px;
}
.carousel-control.left, .carousel-control.right {
	background: none;
	color: #000;
}
.carousel-control.left{
	margin-left: -60px;
}
.carousel-control.right{
	margin-right: -60px;
}
.carousel-inner .row img {
	display: inline-block; 
	max-height: 100px;
	max-width: 150px;
	vertical-align: middle;
}
.carousel-inner .row>div {
    white-space: nowrap;
    text-align: center; 
    margin: 1em 0;
}
.strategy-line .carousel-indicators {
	bottom: -30px;
}
.strategy-line .carousel-indicators li{
 	border: 1px solid #000;
	background-color: #fff;
}
.strategy-line .carousel-indicators li.active{
 	border: 1px solid #fff;
	background-color: #000;
}
</style>

<div id="carousel-<?php echo $content->__get('id')?>" class="carousel slide strategy-line" data-ride="carousel">
  <!-- Indicators -->
  
  <ol class="carousel-indicators">
  <?php $i=0; foreach ($elements as $page){?>
    <li data-target="#carousel-<?php echo $content->__get('id')?>" data-slide-to="<?php echo $i;?>" class="<?php if($i==0) echo "active";?>"></li>
  <?php $i++;}?>
  </ol>

<!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  <?php $i=0; foreach ($elements as $arr){?>
  	<div class="item pages<?php if($i==0) echo " active";?>" page-id="<?php echo $arr[0]->__get('id');?>">
  	  <div class="fill">
        <div class="c" style="text-align:center;">
        	<div class="row">
          <?php foreach ($arr as $k=>$page){?>
				<div class="col-md-<?php echo floor(12/count($arr));?>">
					<span class="helper"></span>
					<img alt="" src="<?php echo $page->__get('url');?>">
				</div>
          <?php }?>
          </div>
        </div>
      </div>
    </div>
  <?php $i++;}?>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" carousel-<?php echo $content->__get('id')?>href="#carousel-<?php echo $content->__get('id')?>" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-<?php echo $content->__get('id')?>" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
	
	
<?php }else{?>

<style>
html,body{height:100%;}
.carousel,.item,.active{height:100%;}
.carousel-inner{height:100%;}
.fill{width:100%;height:100%;background-position:center;background-size:cover;}
#carousel-<?php echo $content->__get('id')?> {
	height: 500px;
}
</style>


<input type="button" id="addPageButton" class="btn btn-success" value="Добавить страницу карусели" data-toggle="modal" data-target="#addCarouselPage">
<?php if(count($content->__get('TsvCarouselElements'))){?>
	&nbsp; <input type="button" id="editPageButton" class="btn btn-warning" value="Редактировать текущую страницу" data-toggle="modal" data-target="#addCarouselPage">
	&nbsp; <input type="button" id="removePageButton" class="btn btn-danger" value="Удалить текущую страницу" data-toggle="modal">
	&nbsp; <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#bgs" aria-expanded="false" aria-controls="bgs">Фоновые изображения</button>
<?php }?>
<br><br>

<div class="collapse" id="bgs">
  <div class="well">
   <iframe src="<?php echo $this->url("zfcadmin/tsv-directory/uploader-form",array("id"=>$content->__get('Content')->__get('id'),"entity_parent"=>"TsvCarousel","entity_store"=>"TsvCarouselImage")) ?>?rand=<?php echo rand(-65534, 65534)?>" width="100%" height="460">Ваш браузер не поддерживает плавающие фреймы!</iframe>
  </div>
</div>

 

<div id="carousel-<?php echo $content->__get('id')?>" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  
  <ol class="carousel-indicators">
  <?php $i=0; foreach ($content->__get('TsvCarouselElements') as $page){?>
    <li data-target="#carousel-example-generic" data-slide-to="<?php echo $i;?>" class="<?php if($i==0) echo "active";?>"></li>
  <?php $i++;}?>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  <?php $i=0; foreach ($content->__get('TsvCarouselElements') as $page){?>
  	<div class="item pages <?php if($i==0) echo "active";?>" page-id="<?php echo $page->__get('id');?>">
  	  <div class="fill" style="background-image:url('<?php foreach ($page->Background as $back) {echo $back->__get('url');break;}?>');">
        <div class="container">
          <?php echo $page->__get('content');?>
        </div>
      </div>
    </div>
  <?php $i++;}?>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-<?php echo $content->__get('id')?>" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-<?php echo $content->__get('id')?>" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<script>

	var addPageUrl = '<?php echo $this->url('zfcadmin/tsv-directory/carousel-add-page',array("carousel_id"=>$content->__get('id')));?>';

	$('#addPageButton').click(function(){
		$('#PageForm').prop('action',addPageUrl);
		$('#edited-item').html('');
		$('.modal-title').html('Добавить страницу в карусель');
		CKEDITOR.instances.CarouselContent.editable().setHtml('');
		unsetBack('#edit-carousel-<?php echo $content->__get('id')?>');
	});
	$('#editPageButton').click(function(){

		html = $(".pages.active .fill .container").html();
		
		$('#PageForm').prop('action',addPageUrl.replace(/add\/page/,"edit/page")+'/'+$(".pages.active").attr('page-id'));
		$('#edited-item').html(html);
		CKEDITOR.instances.CarouselContent.editable().setHtml(html);
		$('#CarouselContent').val(html);
		var url = $(".pages.active .fill").css('background-image').replace(/url/,"");
		$(".back_check[src='"+url.substring(1, url.length-1)+"']").click();
		$('.modal-title').html('Изменить страницу');
	});

	$('#removePageButton').click(function(){
		if(confirm('Вы действительно хотите удалить текущую страницу?'))
			window.location.href=addPageUrl.replace(/add\/page/,"remove/page")+'/'+$(".pages.active").attr('page-id');
	});
</script>

<div class="modal fade" id="addCarouselPage">
  <div class="modal-dialog">
<form id="PageForm" action="<?php echo $this->url('zfcadmin/tsv-directory/carousel-add-page',array("carousel_id"=>$content->__get('id')));?>" method="POST">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Добавить страницу в карусель</h4>
      </div>
      <div class="modal-body">

      	<div class="row">
			<div class="col-md-11">
				Выбор бэкграунда
				<?php foreach ($content->__get('TsvCarouselImages') as $image){?>
					<img class="back_check" src="<?php echo $image->__get('url');?>" height="30" 
					onclick="setBack(this.src,'#edit-carousel-<?php echo $content->__get('id')?>',<?php echo $image->__get('id');?>)">
				<?php }?>
				
				<input type="hidden" id="selected_back" name="selected_back">
			</div>
      	</div>
      	<br>
      	<textarea name="CarouselContent" id="CarouselContent"><?php if(isset($content_arr['CarouselContent'])) echo $content_arr['CarouselContent'];?></textarea>
      	<br>

				<div id="edit-carousel-<?php echo $content->__get('id')?>" class="carousel slide" data-ride="carousel">
				  <!-- Indicators -->
				  <ol class="carousel-indicators">
				    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
				    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
				  </ol>
				
				  <!-- Wrapper for slides -->
				  <div class="carousel-inner" role="listbox">
				    <div class="item active" id="edited-item">
				      <img width="100%" data-src="holder.js/900x500/auto/#666:#666" alt="900x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDkwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzY2NiIvPjxnPjx0ZXh0IHg9IjM0MC45OTIxODc1IiB5PSIyNTAiIHN0eWxlPSJmaWxsOiM2NjY7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6NDJwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj45MDB4NTAwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true">
				      <div class="carousel-caption">
				        Carousel caption
				      </div>
				    </div>
				  </div>
				
				  <!-- Controls -->
				  <a class="left carousel-control" href="#edit-carousel-<?php echo $content->__get('id')?>" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#edit-carousel-<?php echo $content->__get('id')?>" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>
      	
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
        <button type="submit" class="btn btn-siccess">Сохранить</button>
      </div>
</form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->

</div>

<style>
<!--
body .modal {
    width: 90%;
    /* must be half of the width, minus scrollbar on the left (30px) */
    margin-left: 5%;
}
.modal-dialog {
    width: 100%;
}

.back_check {
	cursor: pointer;
}
.transparent25 {
    filter: alpha(Opacity=25);
    opacity: 0.25; 
}
-->
</style>

<script>

// CKEDITOR.plugins.add( 'timestamp', {
//     icons: 'timestamp',
//     init: function( editor ) {
//         editor.addCommand( 'insertTimestamp', {
//             exec: function( editor ) {
//                 var now = new Date();
//                 editor.insertHtml( 'The current date and time is: <em>' + now.toString() + '</em>' );
//             }
//         });
//         editor.ui.addButton( 'Timestamp', {
//             label: 'Insert Timestamp',
//             command: 'insertTimestamp',
//             toolbar: 'insert'
//         });
//     }
// });

$('.collapse').collapse({
  toggle: false
});

CKEDITOR.replace( 'CarouselContent', {
	allowedContent : true //, extraPlugins: 'timestamp'
});


for (var i in CKEDITOR.instances) {
    CKEDITOR.instances[i].on('change', function() {
        $('#edited-item').html(CKEDITOR.instances.CarouselContent.getData());
     });
}

function setBack(src,id,image_id)
{
	$(id).css('background', 'url('+src+')');
	$(id).css('background-size', '100% auto');
	$('#selected_back').val(image_id);
}

function unsetBack(id)
{
	$(id).css('background-image', 'none');
	$('#selected_back').val('');
	$('#edited-item').html('<img class="transparent25" width="100%" data-src="holder.js/900x500/auto/#666:#666" alt="900x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDkwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzY2NiIvPjxnPjx0ZXh0IHg9IjM0MC45OTIxODc1IiB5PSIyNTAiIHN0eWxlPSJmaWxsOiM2NjY7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6NDJwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj45MDB4NTAwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true"><div class="carousel-caption">Carousel caption</div>');
}

</script>
<?php }?>



<h4>Параметры карусели</h4>
<form method="POST">
<input type="text" name="entity" value="TsvCarousel">
<input type="text" name="entity_id" value="<?php echo $content->__get('id');?>">
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Параметр настройки</th>
			<th>Значение параметра</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				Высота карусели (px)
			</td>
			<td>
				<input type="text" name="height" value="<?php echo $content->__get('height');?>">
			</td>
		</tr>
		<?php if($content->__get('strategy')==2){?>
		<tr>
			<td>
				Количество картинок на одной странице (1-12)
			</td>
			<td>
				<input type="text" name="count_on_page" value="<?php echo $content->__get('count_on_page');?>">
			</td>
		</tr>
		<?php }?>
	</tbody>
</table>
<input type="submit" class="btn" value="Сохранить">
</form>
