<?php if(!isset($content_arr)) $content_arr = array();?>
<h1><?if (!isset($content_arr['TsvKey'])) echo "Добавить"; else echo "Редактировать"?> контент 
<?php if(!isset($content_arr['TsvKey'])) $content_arr['TsvKey'] = null;?>
<?php echo $content_arr['TsvKey'];?> в разделе "<?php echo $secName;?>"</h1>

<form method="post" style="margin: 30px 0px 20px 0px;">

<?php if(isset($this->b64TsvKey))
	$content_arr['TsvKey'] = $this->b64TsvKey;?>

<div class="row">
	<div class="col-md-1" style="font-size:18px;margin-top:5px;">
    	Имя
	</div>
	<div class="col-md-11">
		<div class="input-group">
		  <span class="input-group-addon"><?php echo $secName;?> / </span>
	    	<input class="form-control" type="text" id="TsvKey" name="TsvKey" 
	    	placeholder="Имя для использования в шаблонах" value="<?php echo $content_arr['TsvKey'];?>" required>
		</div>

	</div>
</div>
<?php echo $this->partial('partials/'.$content_type, array('sections' => $this->sections,'selectedSection'=>$secId,'content_arr'=>$content_arr));?>
<div class="row" style="margin-top:30px;">
	<div class="col-md-4">
		<input type="submit" class="btn btn-success" value="Сохранить">
	</div>
	<div class="col-md-4" style="text-align:center;">
		&nbsp;
	</div>
	<div class="col-md-4" style="text-align:right;">
		<a onclick="if(confirm('Отменить сохраненение?')) window.location.href='<?php echo $this->url('zfcadmin/tsv-directory/section-view',array('id'=>$secId));?>'"
		 type="button" class="btn btn-info">Отмена</a>
	</div>
</div>

</form>
