
<h1>Добавить контент в раздел "<?php echo $secName;?>"</h1>

<form method="post" style="margin: 30px 0px 20px 0px;">

<div class="row">
	<div class="span1" style="font-size:18px;margin-top:5px;">
    	Имя
	</div>
	<div>
    	<input class="input" id="disabledInput" type="text" placeholder="<?php echo $secName;?>" disabled> / <input class="input-xlarge"
    	 type="text" id="TsvKey" name="TsvKey" placeholder="Имя для использования в шаблонах" required>
	</div>
</div>
<?php echo $this->partial('partials/'.$content_type, array('sections' => $this->sections,'selectedSection'=>$secId));?>
<div class="row" style="margin-top:30px;">
	<div class="span4">
		<input type="submit" class="btn btn-success" value="Сохранить">
	</div>
	<div class="span4" style="text-align:center;">
		&nbsp;
	</div>
	<div class="span4" style="text-align:right;">
		<a onclick="if(confirm('Отменить сохраненение?')) window.location.href='<?php echo $this->url('zfcadmin/tsv-directory/section-view',array('id'=>$secId));?>'"
		 type="button" class="btn btn-info">Отмена</a>
	</div>
</div>

</form>
