



<link href="//serveon.ru/css/admin.css" media="screen" rel="stylesheet" type="text/css">
<?php echo $this->partial('partials/section-list', array('sections' => $this->sections,'selectedSection'=>$this->selectedSection));?>
	  <div class="btn-group pull-right">
        <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">
          Добавить контент <span class="caret"></span>
        </button>
        <ul class="dropdown-menu add-content-btns" role="menu">
          <li><a title="Простой текст или число" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$this->selectedSection,"content_type"=>"TsvStext"));?>"><img src="http://serveon.ru/img/SimpleText.png" alt="Простой текст или число">Простой текст или число</a></li>
          <li><a title="HTML текст" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$this->selectedSection,"content_type"=>"TsvText"));?>"><img src="http://serveon.ru/img/HtmlText.png" alt="HTML-Текст">HTML-Текст</a></li>
          <li><a title="Галерея файлов и изображений" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$this->selectedSection,"content_type"=>"TsvFile"));?>"><img src="http://serveon.ru/img/ImageGalary.png" alt="Галерея файлов">Галерея файлов (изображений)</a></li>
        </ul>
      </div>
<div style="clear:both;"><br></div>

<style>
<!--
.carousel-control.left, .carousel-control.right  {
	background-image: none;
	width: 30px;
}
.carousel-control.left {
	margin-left: -40px;
}
.carousel-control.right {
	margin-right: -40px;
}
.glyphicon-chevron-left, .glyphicon-chevron-right {
	color: black;
}
#carousel-example-generic .item{
	height: 600px;
	overflow-y: auto;
	border:1px solid #ddd;
	border-radius-left:17px;
	padding: 10px;
}

.carousel-indicators {
	bottom:10px;
	-left:50%;
	z-index:15;
	width:100%;
	padding-left:0;
	margin: 0px 0px 15px 0px;
	-text-align:center;
	list-style-type: decimal;
	-top: -60px;
	position: static;
}
.carousel-indicators li{
	height:34px;
	margin:1px;
	margin-left: 10px;
	cursor:pointer;
	background-color:#428bca;
	color: #fff;
	border:1px solid #aaa;
	border-radius:17px;
	padding-top: 5px;
	text-indent: 0px;
}
.carousel-indicators .active{
	height:34px;
	margin:0;
	background-color:#FFAA00;
	color: #fff;
	border-radius:17px;
	margin-left: 10px;
}
.carousel-indicators .active, .carousel-indicators li{
	width: auto;
	padding: 5px 10px 0px 10px;
	margin-top: 7px;
}

-->
</style>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
 <ul class="carousel-indicators">
  <?php 
  $i=0;
  foreach($section->__get('Content') as $row)
	foreach ($row->{$row->content_type} as $content){?>
    <li data-toggle="tooltip" data-placement="bottom" title="<?php echo $row->__get('TsvKey');?>" data-target="#carousel-example-generic" data-slide-to="<?php echo $i;?>" class="tooltips <?php if($i==0){?>active<?php }?>"><?php echo mb_substr($row->__get('TsvKey'), 0/*, 1, 'utf-8'*/);?></li>
  <?php $i++;}?>
 </ul>
    
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
  <?php 
  $i=0;
  foreach($section->__get('Content') as $row){
	foreach ($row->{$row->content_type} as $content){?>
  	<div class="item<?php if($i==0){?> active<?php }?>">
	  	<div class="container-fluid">
	  		<div class="row">
			  <div class="col-md-10">
				 <h1 style="font-weight: bold;size: 32px;"><?php echo $row->__get('TsvKey');?></h1>
			  </div>
			  <div class="col-md-2">
			  	  <div class="btn-group" style="float:right;margin-top:17px;">
			        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
			          Операции <span class="caret"></span>
			        </button>
			        <ul class="dropdown-menu" role="menu">
			          <li><a href="<?php echo $this->url("zfcadmin/tsv-directory/section-edit-content",array("section_id"=>$section->__get('id'),"content_entity_id"=>$row->__get('id'),"content_id"=>$content->__get('id'),"content_type"=>$row->content_type))?>">Править</a></li>
			          <li><a href="<?php echo $this->url("zfcadmin/tsv-directory/section-remove-content",array("section_id"=>$section->__get('id'),"content_id"=>$content->__get('id'),"content_type"=>$row->content_type))?>">Удалить</a></li>
			        </ul>
			      </div>
			  </div>
			</div>
		</div>

		<div class="container-fluid">
	  		<div class="row">
		  		<div class="col-md-12">
					<?php echo $this->partial('partials/View'.$row->content_type, array('content' => $content));?>
		  		</div>
	  		</div>
		</div>
    </div>
  <?php $i++;}}?>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<script type="text/javascript">
<!--
$('.carousel').carousel({
	  interval: 99999999
	});
$('.tooltips').tooltip({});
//-->
</script>



<?php 
// foreach($section->__get('Content') as $row){

// 	foreach ($row->{$row->content_type} as $content)
// 	{
// 		echo "<hr>";

// 	}

// }?>


