



<link href="//serveon.ru/css/admin.css" media="screen" rel="stylesheet" type="text/css">
<?php echo $this->partial('partials/section-list', array('sections' => $this->sections,'selectedSection'=>$this->selectedSection));?>
	  <div class="btn-group pull-right">
        <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">
          Добавить контент <span class="caret"></span>
        </button>
        <ul class="dropdown-menu add-content-btns" role="menu">
          <li><a title="Простой текст или число" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$this->selectedSection,"content_type"=>"TsvStext"));?>"><img src="http://serveon.ru/img/SimpleText.png" alt="Простой текст или число">Простой текст или число</a></li>
          <li><a title="HTML текст" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$this->selectedSection,"content_type"=>"TsvText"));?>"><img src="http://serveon.ru/img/HtmlText.png" alt="HTML-Текст">HTML-Текст</a></li>
          <li><a title="Галерея файлов и изображений" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$this->selectedSection,"content_type"=>"TsvFile"));?>"><img src="http://serveon.ru/img/ImageGalary.png" alt="Галерея файлов">Галерея файлов (изображений)</a></li>
          <li><a title="Карусель" href="<?php echo $this->url("zfcadmin/tsv-directory/section-add-content", array("section_id"=>$this->selectedSection,"content_type"=>"TsvCarousel"));?>"><img src="http://serveon.ru/img/Carousel.png" alt="Карусель">Карусель</a></li>
        </ul>
      </div>
<div style="clear:both;"><br></div>

<div role="tabpanel" id="mainTab">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
  <?php 
  $i=0;
  foreach($section->__get('Content') as $row)
	foreach ($row->{$row->content_type} as $content){?>
	<li role="presentation" class="<?php if($i==0){?>active<?php }?>"><a href="#tab-<?php echo $i;?>" aria-controls="#tab-<?php echo $i;?>" role="tab" data-toggle="tab"><?php echo $row->__get('TsvKey');?></a></li>
  <?php $i++;}?>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
  
    <?php 
  $i=0;
  foreach($section->__get('Content') as $row){
	foreach ($row->{$row->content_type} as $content){?>
	<div role="tabpanel" class="tab-pane <?php if($i==0){?> active<?php }?>" id="<?php echo "tab-".$i;?>">

	  	<div class="container-fluid">
	  		<div class="row">
			  <div class="col-md-10">
				 <h1 style="font-weight: bold;size: 32px;"><?php echo $row->__get('TsvKey');?></h1>
			  </div>
			  <div class="col-md-2">
			  	  <div class="btn-group" style="float:right;margin-top:17px;">
			        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
			          Операции <span class="caret"></span>
			        </button>
			        <ul class="dropdown-menu" role="menu">
			          <li><a href="<?php echo $this->url("zfcadmin/tsv-directory/section-edit-content",array("section_id"=>$section->__get('id'),"content_entity_id"=>$row->__get('id'),"content_id"=>$content->__get('id'),"content_type"=>$row->content_type))?>">Править</a></li>
			          <li><a href="<?php echo $this->url("zfcadmin/tsv-directory/section-remove-content",array("section_id"=>$section->__get('id'),"content_id"=>$content->__get('id'),"content_type"=>$row->content_type))?>">Удалить</a></li>
			        </ul>
			      </div>
			  </div>
			</div>
		</div>

		<div class="container-fluid">
	  		<div class="row">
		  		<div class="col-md-12">
					<?php echo $this->partial('partials/View'.$row->content_type, array('content' => $content));?>
		  		</div>
	  		</div>
		</div>
    </div>
  <?php $i++;}}?>
  


</div>




<script type="text/javascript">
<!--
$(function () {
  $('#mainTab a').tab('show')
})

$('.carousel').carousel({
	  interval: 99999999
	});
$('.tooltips').tooltip({});
//-->
</script>






